# Generated by Django 5.2.3 on 2025-08-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_Specialization', models.CharField(max_length=100)),
                ('doc_image', models.ImageField(upload_to='doctors/')),
                ('doctor_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.departments')),
            ],
        ),
    ]
